### ISSUE TITLE
Variable naming issue

### ISSUE THREAD

**Issue by aminnj** [GOAT-AI-lab/GOAT-Storytelling-Agent#2]
I think these need to be renamed to match the variable name in `prompts.py`

https://github.com/GOAT-AI-lab/GOAT-Storytelling-Agent/blob/6a3620a8c0babeba4151412d3c016fe2d7aa8ca9/goat_storytelling_agent/storytelling_agent.py#L113-L115

`missing_prompts` -> `missing_field_prompt`

**Comment by alisher-amantay** [comment]
Hi, @aminnj. Thank you for pointing that out, your suggestion has been merged.
