### ISSUE TITLE
prompts error

### ISSUE THREAD

**Issue by Yiximail** [GOAT-AI-lab/GOAT-Storytelling-Agent#8]
https://github.com/GOAT-AI-lab/GOAT-Storytelling-Agent/blob/6d315078e14e0825071b01749bd24ae96b8cca11/goat_storytelling_agent/prompts.py#L24-L26

`time\Event:` Missed an n.

**Comment by alisher-amantay** [comment]
thank you for pointing that out, fixed in #10
